# Generated by Django 4.0.4 on 2022-05-02 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WBC', models.CharField(default=None, max_length=10, null=True)),
                ('Neut', models.CharField(default=None, max_length=10, null=True)),
                ('Lymph', models.CharField(default=None, max_length=10, null=True)),
                ('RBC', models.CharField(default=None, max_length=10, null=True)),
                ('HCT', models.CharField(default=None, max_length=10, null=True)),
                ('Urea', models.CharField(default=None, max_length=10, null=True)),
                ('Hb', models.CharField(default=None, max_length=10, null=True)),
                ('Crtn', models.CharField(default=None, max_length=10, null=True)),
                ('Iron', models.CharField(default=None, max_length=10, null=True)),
                ('HDL', models.CharField(default=None, max_length=10, null=True)),
                ('AP', models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=8, null=True)),
                ('user_id', models.CharField(max_length=9, null=True)),
                ('password', models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=8, null=True)),
                ('lastName', models.CharField(default=None, max_length=8, null=True)),
                ('patient_id', models.CharField(default=None, max_length=9, null=True)),
                ('age', models.CharField(default=None, max_length=9, null=True)),
                ('gender', models.CharField(default=None, max_length=9, null=True)),
                ('smoke', models.BooleanField(default=False, null=True)),
                ('eastCommunity', models.BooleanField(default=False, null=True)),
                ('pregnancy', models.BooleanField(default=False, null=True)),
                ('ethiopian', models.BooleanField(default=False, null=True)),
                ('medicine', models.BooleanField(default=False, null=True)),
                ('diagnose', models.CharField(default=None, max_length=300, null=True)),
                ('treatment', models.CharField(default=None, max_length=500, null=True)),
                ('bloodTest', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.bloodtest')),
            ],
        ),
    ]
