# Generated by Django 3.2.9 on 2022-04-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=8, null=True)),
                ('user_id', models.CharField(max_length=9, null=True)),
                ('password', models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
    ]
